plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/djaouad/ai-customer-support-agent/out"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
base = "/home/djaouad/ai-customer-support-agent/frontend"

[build.environment]
NEXT_PUBLIC_API_URL = "https://ai-customer-support-backend.onrender.com"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]