headersOrigin = "inline"
redirectsOrigin = "inline"

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/home/djaouad/ai-customer-support-agent/frontend/out"
publishOrigin = "config"
commandOrigin = "config"
base = "/home/djaouad/ai-customer-support-agent/frontend"
command = "npm run build"

[build.environment]
NEXT_PUBLIC_API_URL = "https://ai-customer-support-backend-ldbf.onrender.com"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image/"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_next/image/"
to = "/.netlify/images"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]